name: Project_12746
channels:
  - conda-forge
  - defaults
dependencies:
  - PyPDF2
  - pdfplumber
  - nltk
  - scikit-learn
  - networkx
  - matplotlib
  - spacy
post-build:
  - python -m spacy download en_core_web_sm