name: proj_12746
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - PyPDF2
  - pdfplumber
  - nltk
  - scikit-learn
  - networkx
  - matplotlib
  - spacy
<<<<<<< HEAD
  - pyyaml
=======
  - pyyaml
post-build:
  - python -m spacy download en_core_web_sm
>>>>>>> 468dd4f (update web)
