paths:
  data_folder: "../data"
  output_file: "../results/temperature_sentences.txt"
  classified_output_folder: "../results/classified_sentences/"

keywords:
  failure_keywords:
    - "failure"
    - "malfunction"
    - "loss of coolant"
    - "reactor overheat"
    - "pressure boundary degradation"
    - "crack"
    - "corrosion"
    - "high temperature"
    - "overpressure"
  countermeasure_keywords:
    - "shutdown"
    - "isolation"
    - "emergency cooling"
    - "injection"
    - "pressure relief"
    - "backup system"
    - "monitoring"
    - "relief valve"
    - "reactor core isolation cooling system"
    - "emergency core cooling system"
  preventive_keywords:
    - "prevention"
    - "regular inspection"
    - "monitoring"
    - "redundancy"
    - "material selection"
    - "design considerations"
    - "regulations"
    - "compliance"
    - "General Design Criteria"