paths:
  data_folder: "../data"
  output_file: "../results/temperature_sentences.txt"

keywords:
  temperature_related: 
    - "temperature"
    - "heat"
    - "cooling"
    - "thermal"
    - "overheat"
    - "overheating"
    - "coolant"
    - "hot"

options:
  add_timestamp: false